fail_fast: true
repos:
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21-2
  hooks:
  - id: isort
    additional_dependencies: ["toml"]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    args: [--config=./pyproject.toml]

- repo: https://gitlab.com/retnikt/flake9
  rev: 3.8.3.post1
  hooks:
  - id: flake8
    additional_dependencies: ['toml', 'flake8-comprehensions', 'flake8-rst-docstrings']

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.770'
  hooks:
  - id: mypy
    exclude: >
      (?x)^(
        .*/migrations/.*
      )$
