# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='ssh-mgr',
    version='0.1.1',
    description='A Tool to manage ssh connection',
    python_requires='==3.*,>=3.6.0',
    author='shabbywu',
    author_email='shabbywu@tencent.com',
    license='MIT',
    keywords='ssh',
    entry_points={"console_scripts": ["ssh2 = ssh2.cli.main:cli"]},
    packages=['ssh2', 'ssh2.cli', 'ssh2.models', 'ssh2.plugins', 'ssh2.utils'],
    package_dir={"": "."},
    package_data={},
    install_requires=['aenum==2.2.2', 'click>=7.0', 'cryptography==2.8', 'pyyaml==5.1.2', 'sqlalchemy==1.3.10'],
    extras_require={"dev": ["pytest==3.*,>=3.0.0", "pytest-cov==2.*,>=2.4.0"]},
)
